In [2]:
# binarization
from sklearn.preprocessing import Binarizer
import pandas
import numpy

In [3]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv("diabetes.csv")


In [4]:
array = dataframe.values
# separate array into input and output components
X = array[:,0:8]
Y = array[:,8]


In [5]:
binarizer = Binarizer(threshold=0.0).fit(X)
binaryX = binarizer.transform(X)


In [6]:
# summarize transformed data
numpy.set_printoptions(precision=3)
print(binaryX[0:5,:])

[[1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1.]]
