In [2]:
import pandas 
import scipy
import numpy
from sklearn.preprocessing import MinMaxScaler

In [7]:
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [3]:
dataframe = pandas.read_csv("diabetes.csv")

In [9]:
# Rescale data (between 0 and 1)
array = dataframe.values

In [10]:
# separate array into input and output components

X = array[:,0:8]
Y = array[:,8]

In [11]:
scaler = MinMaxScaler(feature_range=(0, 1))
rescaledX = scaler.fit_transform(X)

In [12]:
# summarize transformed data
numpy.set_printoptions(precision=3)
print(rescaledX[0:5,:])

[[0.353 0.744 0.59  0.354 0.    0.501 0.234 0.483]
 [0.059 0.427 0.541 0.293 0.    0.396 0.117 0.167]
 [0.471 0.92  0.525 0.    0.    0.347 0.254 0.183]
 [0.059 0.447 0.541 0.232 0.111 0.419 0.038 0.   ]
 [0.    0.688 0.328 0.354 0.199 0.642 0.944 0.2  ]]
